export const mockSharpeners = [
  {
    id: "1",
    name: "Sharp Edge Cutlery",
    location: "Seattle, WA",
    zipCode: "98101",
    distance: "2.3 miles",
    rating: 4.8,
    reviewCount: 24,
    services: ["Kitchen Knives", "Pocket Knives", "Scissors"],
    specialties: ["Japanese Knives", "German Steel"],
    phone: "(206) 555-0123",
    website: "sharpedgecutlery.com",
    description:
      "Professional knife sharpening with 15+ years experience. Specializing in high-end kitchen knives and collector pieces.",
    priceRange: "$8-15 per knife",
    turnaround: "Same day",
  },
  {
    id: "2",
    name: "Blade Masters",
    location: "Portland, OR",
    zipCode: "97201",
    distance: "1.8 miles",
    rating: 4.6,
    reviewCount: 18,
    services: ["Kitchen Knives", "Garden Tools", "Scissors"],
    specialties: ["Ceramic Knives", "Serrated Edges"],
    phone: "(503) 555-0456",
    website: "blademasters.com",
    description: "Family-owned business serving Portland for over 20 years. Mobile service available.",
    priceRange: "$6-12 per knife",
    turnaround: "1-2 days",
  },
  {
    id: "3",
    name: "Precision Sharpening",
    location: "San Francisco, CA",
    zipCode: "94102",
    distance: "0.5 miles",
    rating: 4.9,
    reviewCount: 31,
    services: ["Kitchen Knives", "Pocket Knives", "Garden Tools", "Scissors"],
    specialties: ["Professional Chef Knives", "Antique Restoration"],
    phone: "(415) 555-0789",
    website: "precisionsharpening.com",
    description: "Award-winning sharpening service trusted by top restaurants and culinary schools.",
    priceRange: "$10-20 per knife",
    turnaround: "2-3 days",
  },
  {
    id: "4",
    name: "Mobile Blade Pro",
    location: "Austin, TX",
    zipCode: "78701",
    distance: "3.2 miles",
    rating: 4.7,
    reviewCount: 42,
    services: ["Kitchen Knives", "Pocket Knives", "Garden Tools", "Scissors", "Hunting Knives"],
    specialties: ["Mobile Service", "Same-Day Service"],
    phone: "(512) 555-0234",
    website: "mobilebladepro.com",
    description: "Convenient mobile sharpening service. We come to you! Serving Austin and surrounding areas.",
    priceRange: "$7-14 per knife",
    turnaround: "Same day",
  },
  {
    id: "5",
    name: "The Knife Doctor",
    location: "Denver, CO",
    zipCode: "80202",
    distance: "4.1 miles",
    rating: 4.5,
    reviewCount: 67,
    services: ["Kitchen Knives", "Pocket Knives", "Scissors", "Hunting Knives"],
    specialties: ["Damaged Blade Repair", "Handle Restoration"],
    phone: "(303) 555-0567",
    website: "knifedoctor.com",
    description: "Expert blade restoration and sharpening. We fix what others can't! Over 25 years experience.",
    priceRange: "$9-18 per knife",
    turnaround: "3-5 days",
  },
  {
    id: "6",
    name: "Artisan Edge Works",
    location: "Nashville, TN",
    zipCode: "37201",
    distance: "2.7 miles",
    rating: 4.9,
    reviewCount: 28,
    services: ["Kitchen Knives", "Pocket Knives", "Scissors"],
    specialties: ["Custom Sharpening Angles", "Japanese Water Stones"],
    phone: "(615) 555-0890",
    website: "artisanedgeworks.com",
    description:
      "Artisan-level sharpening using traditional Japanese techniques. Each blade is treated as a work of art.",
    priceRange: "$12-25 per knife",
    turnaround: "1-2 days",
  },
  {
    id: "7",
    name: "Quick Sharp Solutions",
    location: "Phoenix, AZ",
    zipCode: "85001",
    distance: "1.2 miles",
    rating: 4.3,
    reviewCount: 89,
    services: ["Kitchen Knives", "Scissors", "Garden Tools"],
    specialties: ["Volume Discounts", "Restaurant Service"],
    phone: "(602) 555-0345",
    website: "quicksharpsolutions.com",
    description: "Fast, affordable sharpening for home cooks and restaurants. Volume discounts available.",
    priceRange: "$5-10 per knife",
    turnaround: "Same day",
  },
  {
    id: "8",
    name: "Heritage Blade Care",
    location: "Charleston, SC",
    zipCode: "29401",
    distance: "5.3 miles",
    rating: 4.8,
    reviewCount: 35,
    services: ["Kitchen Knives", "Pocket Knives", "Hunting Knives", "Antique Blades"],
    specialties: ["Antique Restoration", "Historical Blades"],
    phone: "(843) 555-0678",
    website: "heritagebladecare.com",
    description:
      "Specializing in antique and historical blade restoration. Preserving craftsmanship for future generations.",
    priceRange: "$15-35 per knife",
    turnaround: "1-2 weeks",
  },
]

export const mockReviews = [
  {
    id: "1",
    sharpener_id: "1",
    customer_name: "Sarah Johnson",
    customer_email: "sarah@email.com",
    rating: 5,
    review_text: "Excellent service! My knives are sharper than when I first bought them.",
    service_type: "Kitchen Knives",
    created_at: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    sharpener_id: "1",
    customer_name: "Mike Chen",
    customer_email: "mike@email.com",
    rating: 4,
    review_text: "Great work and fast turnaround. Will definitely use again.",
    service_type: "Pocket Knives",
    created_at: "2024-01-10T14:20:00Z",
  },
  {
    id: "3",
    sharpener_id: "4",
    customer_name: "Jessica Martinez",
    customer_email: "jessica@email.com",
    rating: 5,
    review_text: "Mobile service was incredibly convenient! They came right to my restaurant.",
    service_type: "Kitchen Knives",
    created_at: "2024-01-20T09:15:00Z",
  },
  {
    id: "4",
    sharpener_id: "6",
    customer_name: "David Kim",
    customer_email: "david@email.com",
    rating: 5,
    review_text: "Amazing craftsmanship! My Japanese knives have never been sharper.",
    service_type: "Kitchen Knives",
    created_at: "2024-01-18T16:45:00Z",
  },
  {
    id: "5",
    sharpener_id: "3",
    customer_name: "Emily Rodriguez",
    customer_email: "emily@email.com",
    rating: 4,
    review_text: "Professional service and fair pricing. Highly recommended for chefs.",
    service_type: "Kitchen Knives",
    created_at: "2024-01-12T11:30:00Z",
  },
  {
    id: "6",
    sharpener_id: "7",
    customer_name: "Robert Thompson",
    customer_email: "robert@email.com",
    rating: 4,
    review_text: "Quick and affordable. Perfect for my home kitchen needs.",
    service_type: "Kitchen Knives",
    created_at: "2024-01-22T14:20:00Z",
  },
]
