-- Seed data for sharpeners table
INSERT INTO sharpeners (
  business_name, 
  owner_name, 
  email, 
  phone, 
  address, 
  city, 
  state, 
  zip_code, 
  website, 
  description, 
  services, 
  specialties, 
  pricing_info, 
  years_experience, 
  mobile_service, 
  pickup_delivery, 
  subscription_status
) VALUES 
(
  'Sharp Edge Pro',
  'Mike Johnson',
  'mike@sharpedgepro.com',
  '(555) 123-4567',
  '123 Main Street',
  'Seattle',
  'WA',
  '98101',
  'https://sharpedgepro.com',
  'Professional knife sharpening service with over 15 years of experience. We specialize in kitchen knives, chef tools, and outdoor equipment.',
  ARRAY['Kitchen Knives', 'Chef Tools', 'Outdoor Knives', 'Scissors'],
  ARRAY['Japanese Knives', 'German Steel', 'Ceramic Blades'],
  '$8-$25 per knife',
  15,
  true,
  true,
  'active'
),
(
  'Blade Masters',
  'Sarah Chen',
  'sarah@blademasters.com',
  '(555) 987-6543',
  '456 Oak Avenue',
  'Portland',
  'OR',
  '97201',
  'https://blademasters.com',
  'Family-owned sharpening business serving the Portland area for over 20 years. Expert restoration of vintage and antique blades.',
  ARRAY['Kitchen Knives', 'Antique Restoration', 'Scissors', 'Garden Tools'],
  ARRAY['Vintage Restoration', 'Hand Forged Blades', 'Custom Handles'],
  '$10-$35 per item',
  22,
  false,
  true,
  'active'
),
(
  'Quick Sharp Mobile',
  'David Rodriguez',
  'david@quicksharpmobile.com',
  '(555) 456-7890',
  '789 Pine Street',
  'San Francisco',
  'CA',
  '94102',
  'https://quicksharpmobile.com',
  'Mobile knife sharpening service bringing professional results to your doorstep. Same-day service available.',
  ARRAY['Kitchen Knives', 'Barber Tools', 'Outdoor Knives', 'Scissors'],
  ARRAY['Mobile Service', 'Same Day Service', 'Professional Grade'],
  '$12-$30 per knife',
  8,
  true,
  false,
  'active'
),
(
  'Precision Edge',
  'Lisa Thompson',
  'lisa@precisionedge.com',
  '(555) 321-0987',
  '321 Cedar Lane',
  'Denver',
  'CO',
  '80202',
  'https://precisionedge.com',
  'Precision sharpening for culinary professionals and home cooks. We use advanced equipment for perfect angles every time.',
  ARRAY['Kitchen Knives', 'Chef Tools', 'Meat Processing', 'Scissors'],
  ARRAY['Culinary Professional', 'Precision Angles', 'Commercial Grade'],
  '$15-$40 per knife',
  12,
  false,
  true,
  'active'
),
(
  'Mountain Sharp',
  'Tom Wilson',
  'tom@mountainsharp.com',
  '(555) 654-3210',
  '654 Mountain View Road',
  'Boulder',
  'CO',
  '80301',
  'https://mountainsharp.com',
  'Specializing in outdoor and hunting knives. Expert in maintaining tactical and survival blades for outdoor enthusiasts.',
  ARRAY['Outdoor Knives', 'Hunting Knives', 'Tactical Blades', 'Multi-tools'],
  ARRAY['Outdoor Specialist', 'Tactical Blades', 'Survival Gear'],
  '$10-$45 per knife',
  18,
  true,
  true,
  'active'
);

-- Fixed sharpener_id references to use the correct UUIDs from inserted records
-- Seed data for reviews table
INSERT INTO reviews (
  sharpener_id,
  customer_name,
  customer_email,
  rating,
  review_text,
  service_type
) VALUES 
((SELECT id FROM sharpeners WHERE email = 'mike@sharpedgepro.com'), 'Jennifer Adams', 'jennifer@email.com', 5, 'Excellent service! My knives are sharper than when I first bought them. Mike is very professional and knowledgeable.', 'Kitchen Knives'),
((SELECT id FROM sharpeners WHERE email = 'mike@sharpedgepro.com'), 'Robert Kim', 'robert@email.com', 5, 'Outstanding work on my Japanese chef knives. Very careful handling and perfect results.', 'Japanese Knives'),
((SELECT id FROM sharpeners WHERE email = 'mike@sharpedgepro.com'), 'Maria Garcia', 'maria@email.com', 4, 'Great mobile service. Convenient and professional. Will definitely use again.', 'Kitchen Knives'),
((SELECT id FROM sharpeners WHERE email = 'sarah@blademasters.com'), 'John Smith', 'john@email.com', 5, 'Sarah did an amazing job restoring my grandfather''s vintage hunting knife. Looks brand new!', 'Antique Restoration'),
((SELECT id FROM sharpeners WHERE email = 'sarah@blademasters.com'), 'Emily Davis', 'emily@email.com', 5, 'Best sharpening service in Portland. Family business with incredible attention to detail.', 'Kitchen Knives'),
((SELECT id FROM sharpeners WHERE email = 'david@quicksharpmobile.com'), 'Michael Brown', 'michael@email.com', 4, 'Quick and convenient mobile service. David arrived on time and did great work.', 'Kitchen Knives'),
((SELECT id FROM sharpeners WHERE email = 'david@quicksharpmobile.com'), 'Lisa Johnson', 'lisa@email.com', 5, 'Same-day service was a lifesaver for my restaurant. Professional quality work.', 'Chef Tools'),
((SELECT id FROM sharpeners WHERE email = 'lisa@precisionedge.com'), 'Chef Martinez', 'chef@restaurant.com', 5, 'Precision Edge lives up to their name. Perfect angles on all my professional knives.', 'Chef Tools'),
((SELECT id FROM sharpeners WHERE email = 'lisa@precisionedge.com'), 'Amanda White', 'amanda@email.com', 5, 'Lisa is incredibly knowledgeable and does beautiful work. Highly recommended!', 'Kitchen Knives'),
((SELECT id FROM sharpeners WHERE email = 'tom@mountainsharp.com'), 'Hunter Jake', 'jake@email.com', 5, 'Tom knows outdoor knives better than anyone. My hunting knives have never been sharper.', 'Hunting Knives'),
((SELECT id FROM sharpeners WHERE email = 'tom@mountainsharp.com'), 'Outdoor Steve', 'steve@email.com', 4, 'Great work on my tactical blades. Tom understands what outdoor enthusiasts need.', 'Tactical Blades');
